---
- name: Testing DB SERVER
  hosts: dbserver
  environment:
    http_proxy: proxy
    https_proxy: proxy
  become: yes
  become_user: root
  become_method: sudo

  tasks:

   - name: Download MySql Community Repo
     get_url:
       url: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
       dest: /home/centos
   - name: Install MySQL Community Repo
     command: sudo /usr/bin/rpm -ivh mysql-community-release-el7-7.noarch.rpm
   - name: Install MySQL Server
     yum: name=mysql-server state=present
   - name: Install MySQLPython
     yum: name=MySQL-python state=present
   - name: Start MYSQL SERVER AND ENABLE IT
     service: name=mysqld state=started enabled=yes
   - name: Remove Test Database
     mysql_db: name=test state=absent
   - name: REmove All anonymous USER account
     mysql_user: name='' host_all=yes state=absent
   - name: Output ansible hostname
     debug: msg="Hostname is {{ansible_hostname}}"
   - name: Change Root Password
     mysql_user: name=root host=localhost password=123
   - name: Previlage
     command: mysql -u root -p123 -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '123' WITH GRANT OPTION;"
