---
- name: Testing WEB SERVER
  hosts: webserver
  environment:
    http_proxy: proxy
    https_proxy: proxy
  become: yes
  become_user: root
  become_method: sudo

  tasks:
   - name: install httpd
     yum:
        name: httpd

   - name: install php and maria db
     yum: name={{item}} state=installed
     with_items:
      - php
      - php-mysql
      - php-pdo
      - php-gd
      - php-mbstring
      - mariadb-server
      - mariadb

#   - name: copy file
#     shell: echo "<?php phpinfo (); ?>" > /var/www/html/info.php

   - name: install mariadb
     yum: name={{item}} state=installed
     with_items:
      - mariadb-server
      - mariadb
   - name: cloning the file
     git:
       repo: 'https://github.com/atul9452/devtools.git'
       dest: /var/www/html
   - name: run script
     shell: 'php install.php'
     args:
       chdir: '/var/www/html/pdo'
   - name: restart httpd
     service:
       name: httpd
       state: restarted
